### ISSUE TITLE
[Refactor] 소셜 로그인 기능 통합을 위한 Repository 패턴 적용

### ISSUE THREAD

**Issue by Gnoam-R** [Gnoam-R/Gnoam-R#1]
## 📌  Refactor Issue
Google Login , kakao Login -> ViewModel의 연결 흐름에서  LoginRepository -> ViewModel 구조로 코드를 리펙토링 합니다.

## 📝  To-do
- [ ] 카카오 소셜 로그인 기능 구현
- [ ] 구글 소셜 로그인 토큰 만료 이슈 해결
- [ ] dogdom 프로젝트 구조 리펙토링 수행
